#!/usr/bin/env node
/*
 * fetch-shops.mjs — pull real Shibuya store data from OpenStreetMap (Overpass)
 * and write it to js/osm-shops.js for the app to load.
 *
 * WHERE THE DATA COMES FROM
 *   OpenStreetMap via the Overpass API — free, no API key, redistributable
 *   under the ODbL. Every element carries a name, coordinates, a shop/amenity
 *   type, and often opening_hours + website.
 *
 * USAGE
 *   node scripts/fetch-shops.mjs                 # default Shibuya bbox
 *   node scripts/fetch-shops.mjs --bbox 35.653,139.693,35.670,139.708
 *   OVERPASS_URL=https://overpass.kumi.systems/api/interpreter node scripts/fetch-shops.mjs
 *
 * Requires internet access (won't run inside a walled-off CI sandbox).
 * Output: js/osm-shops.js  ->  window.OSM_SHOPS = [ ... ]
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dir, "..", "js", "osm-shops.js");

// Default bounding box around the Shibuya shopping district: S,W,N,E
const argBbox = process.argv.includes("--bbox")
  ? process.argv[process.argv.indexOf("--bbox") + 1]
  : "35.6530,139.6930,35.6700,139.7080";
const [S, W, N, E] = argBbox.split(",").map(Number);
const BBOX = `${S},${W},${N},${E}`;

const OVERPASS_URL = process.env.OVERPASS_URL || "https://overpass-api.de/api/interpreter";

// Map raw OSM shop/amenity tags to the app's display categories.
function categorize(t = {}) {
  const shop = t.shop, am = t.amenity, tour = t.tourism;
  if (tour === "viewpoint") return "viewpoint";
  if (["attraction", "artwork", "gallery", "museum"].includes(tour)) return "landmark";
  if (["cafe", "restaurant", "fast_food", "bar", "pub", "food_court"].includes(am)) return "food";
  if (["department_store", "mall"].includes(shop)) return "department";
  if (["clothes", "boutique", "shoes", "bag", "fashion_accessories", "jewelry"].includes(shop)) return "fashion";
  if (["electronics", "mobile_phone", "computer", "camera", "hifi"].includes(shop)) return "electronics";
  if (["music", "musical_instrument"].includes(shop)) return "music";
  if (["books", "anime", "games", "video_games", "toys", "collector", "comic"].includes(shop)) return "otaku";
  if (["variety_store", "gift", "stationery", "convenience", "cosmetics", "department"].includes(shop)) return "variety";
  if (shop) return "variety";
  return "landmark";
}

const QUERY = `
[out:json][timeout:60];
(
  node["shop"]["name"](${BBOX});
  way["shop"]["name"](${BBOX});
  node["amenity"~"^(cafe|restaurant|fast_food|bar|pub)$"]["name"](${BBOX});
  node["tourism"~"^(attraction|viewpoint|gallery|museum)$"]["name"](${BBOX});
);
out center tags;`;

async function main() {
  console.log(`Querying Overpass for Shibuya (${BBOX}) …`);
  const res = await fetch(OVERPASS_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: "data=" + encodeURIComponent(QUERY),
  });
  if (!res.ok) throw new Error(`Overpass HTTP ${res.status}: ${await res.text()}`);
  const json = await res.json();

  const seen = new Set();
  const shops = [];
  for (const el of json.elements) {
    const t = el.tags || {};
    const name = t["name:en"] || t.name;
    if (!name) continue;
    const lat = el.lat ?? el.center?.lat;
    const lng = el.lon ?? el.center?.lon;
    if (lat == null || lng == null) continue;
    const key = name + "@" + lat.toFixed(4) + "," + lng.toFixed(4);
    if (seen.has(key)) continue;
    seen.add(key);
    shops.push({
      id: `osm-${el.type[0]}${el.id}`,
      name,
      jp: t.name && t.name !== name ? t.name : "",
      category: categorize(t),
      lat: +lat.toFixed(6),
      lng: +lng.toFixed(6),
      hours: t.opening_hours || "",
      website: t.website || t["contact:website"] || "",
      osmType: t.shop || t.amenity || t.tourism || "",
    });
  }

  shops.sort((a, b) => a.name.localeCompare(b.name));
  await mkdir(dirname(OUT), { recursive: true });
  const header =
    `/* Auto-generated by scripts/fetch-shops.mjs from OpenStreetMap (© OSM contributors, ODbL).\n` +
    `   bbox=${BBOX}  count=${shops.length}  do not edit by hand. */\n`;
  await writeFile(OUT, header + "window.OSM_SHOPS = " + JSON.stringify(shops, null, 0) + ";\n");
  console.log(`Wrote ${shops.length} shops -> ${OUT}`);
}

main().catch((e) => {
  console.error("Failed:", e.message);
  process.exit(1);
});
