/*
 * Shibuya Walk — curated dataset of notable Shibuya (渋谷) stores & spots.
 *
 * Coordinates are approximate WGS84 (lat, lng) suitable for pedestrian
 * navigation. They are hand-curated from public map data and may be off by a
 * few metres — good enough to walk you to the right building.
 *
 * category values drive filtering + marker colour. Keep them in sync with
 * CATEGORIES below.
 */

const CATEGORIES = {
  landmark:    { label: "Landmark",        color: "#e11d48", icon: "★" },
  viewpoint:   { label: "Viewpoint",       color: "#0ea5e9", icon: "◎" },
  department:  { label: "Department store", color: "#7c3aed", icon: "▣" },
  fashion:     { label: "Fashion",         color: "#db2777", icon: "♦" },
  electronics: { label: "Electronics",     color: "#2563eb", icon: "▤" },
  music:       { label: "Music / records", color: "#f59e0b", icon: "♪" },
  otaku:       { label: "Anime / games",   color: "#16a34a", icon: "◆" },
  variety:     { label: "Variety / goods", color: "#0d9488", icon: "❖" },
  food:        { label: "Food & drink",    color: "#ea580c", icon: "🍜" },
  park:        { label: "Park / open air",  color: "#65a30d", icon: "❀" },
};

/* Each spot: id, name, jp, category, lat, lng, desc, hours (typical), tip */
const SPOTS = [
  {
    id: "hachiko",
    name: "Hachikō Statue",
    jp: "忠犬ハチ公像",
    category: "landmark",
    lat: 35.65900, lng: 139.70058,
    desc: "The famous loyal-dog statue and Shibuya's #1 meeting point, right outside the station's Hachikō exit.",
    hours: "24h (outdoor)",
    tip: "Best starting point — every walking route below begins near here.",
  },
  {
    id: "scramble",
    name: "Shibuya Scramble Crossing",
    jp: "渋谷スクランブル交差点",
    category: "landmark",
    lat: 35.65950, lng: 139.70042,
    desc: "The world's busiest pedestrian crossing — up to 3,000 people cross at once.",
    hours: "24h",
    tip: "Best crowds after dark. View it from Magnet rooftop or the Starbucks in Q-Front.",
  },
  {
    id: "shibuya109",
    name: "SHIBUYA109",
    jp: "SHIBUYA109",
    category: "fashion",
    lat: 35.65947, lng: 139.69835,
    desc: "Iconic cylindrical fashion tower — 10 floors of youth/street women's brands.",
    hours: "10:00–21:00",
    tip: "The building itself is a landmark; go up for trend-spotting.",
  },
  {
    id: "scramble-square",
    name: "Shibuya Scramble Square",
    jp: "渋谷スクランブルスクエア",
    category: "department",
    lat: 35.65799, lng: 139.70168,
    desc: "47-storey tower directly on the station with shops, food halls and the SHIBUYA SKY observation deck.",
    hours: "10:00–21:00",
    tip: "Take the lift to SHIBUYA SKY for the best rooftop view of the crossing.",
  },
  {
    id: "shibuya-sky",
    name: "SHIBUYA SKY",
    jp: "渋谷スカイ",
    category: "viewpoint",
    lat: 35.65790, lng: 139.70170,
    desc: "Open-air rooftop observation deck 230m up, on top of Scramble Square.",
    hours: "10:00–22:30 (last entry 21:20)",
    tip: "Book a timed ticket online; sunset slots sell out.",
  },
  {
    id: "hikarie",
    name: "Shibuya Hikarie",
    jp: "渋谷ヒカリエ",
    category: "department",
    lat: 35.65913, lng: 139.70365,
    desc: "Sleek shopping/culture tower with the ShinQs department store and great food floors.",
    hours: "10:00–21:00",
    tip: "Basement food hall (ShinQs) is excellent for takeaway sweets.",
  },
  {
    id: "stream",
    name: "Shibuya Stream",
    jp: "渋谷ストリーム",
    category: "food",
    lat: 35.65640, lng: 139.70280,
    desc: "Riverside dining/office complex along the reopened Shibuya River.",
    hours: "Restaurants ~11:00–23:00",
    tip: "Nice for a quieter meal away from the crossing crowds.",
  },
  {
    id: "parco",
    name: "Shibuya PARCO",
    jp: "渋谷パルコ",
    category: "department",
    lat: 35.66263, lng: 139.69852,
    desc: "Design-forward mall packed with fashion, art, and a famous otaku floor (6F).",
    hours: "11:00–21:00",
    tip: "6F 'Cyberspace Shibuya' holds Nintendo Tokyo, Pokémon Center & Jump Store.",
  },
  {
    id: "nintendo-tokyo",
    name: "Nintendo TOKYO",
    jp: "Nintendo TOKYO",
    category: "otaku",
    lat: 35.66263, lng: 139.69850,
    desc: "Japan's first official Nintendo store — Mario, Zelda, Splatoon merch galore (PARCO 6F).",
    hours: "11:00–21:00",
    tip: "Weekends get busy; go at opening.",
  },
  {
    id: "pokemon-center",
    name: "Pokémon Center SHIBUYA",
    jp: "ポケモンセンターシブヤ",
    category: "otaku",
    lat: 35.66261, lng: 139.69848,
    desc: "Shibuya's Pokémon flagship, next to Nintendo TOKYO on PARCO 6F.",
    hours: "11:00–21:00",
    tip: "Guarded by a giant Mewtwo — great photo spot.",
  },
  {
    id: "tower-records",
    name: "Tower Records Shibuya",
    jp: "タワーレコード渋谷店",
    category: "music",
    lat: 35.66283, lng: 139.69894,
    desc: "One of the world's largest music stores — 9 floors of CDs, vinyl, J-pop & events.",
    hours: "11:00–22:00",
    tip: "Check the event board; free in-store live shows happen often.",
  },
  {
    id: "mandarake",
    name: "Mandarake Shibuya",
    jp: "まんだらけ渋谷店",
    category: "otaku",
    lat: 35.65965, lng: 139.69745,
    desc: "Basement treasure-trove of used manga, anime cels, figures and collectibles.",
    hours: "12:00–20:00",
    tip: "Down in the BEAM building basement — easy to miss from street level.",
  },
  {
    id: "disk-union",
    name: "Disk Union Shibuya",
    jp: "ディスクユニオン渋谷",
    category: "music",
    lat: 35.66018, lng: 139.69683,
    desc: "Legendary used-record chain — deep crates of rock, jazz, punk and rare vinyl.",
    hours: "11:00–21:00",
    tip: "Multiple genre-specific floors/branches within a couple of blocks.",
  },
  {
    id: "donki",
    name: "MEGA Don Quijote Shibuya",
    jp: "MEGAドン・キホーテ渋谷本店",
    category: "variety",
    lat: 35.66142, lng: 139.69752,
    desc: "Sprawling discount emporium — snacks, cosmetics, souvenirs, oddities, open late.",
    hours: "24h",
    tip: "Best late-night stop for tax-free souvenirs and Kit-Kat flavours.",
  },
  {
    id: "loft",
    name: "Shibuya LOFT",
    jp: "渋谷ロフト",
    category: "variety",
    lat: 35.66332, lng: 139.69788,
    desc: "Six floors of stationery, design goods, gadgets and quirky lifestyle items.",
    hours: "11:00–21:00",
    tip: "Stationery floor is a must for gift shopping.",
  },
  {
    id: "hands",
    name: "Hands Shibuya (Tokyu Hands)",
    jp: "ハンズ渋谷店",
    category: "variety",
    lat: 35.66360, lng: 139.69700,
    desc: "DIY, travel, hobby and lifestyle megastore across a split-level building.",
    hours: "10:00–21:00",
    tip: "Floors are split in half-levels — follow the ramps.",
  },
  {
    id: "bic-camera",
    name: "Bic Camera Shibuya East",
    jp: "ビックカメラ渋谷東口店",
    category: "electronics",
    lat: 35.65790, lng: 139.70110,
    desc: "Big-box electronics: cameras, gadgets, appliances, duty-free counter.",
    hours: "10:00–21:00",
    tip: "Show your passport for tax-free on ¥5,000+ purchases.",
  },
  {
    id: "uniqlo",
    name: "UNIQLO Shibuya",
    jp: "ユニクロ渋谷店",
    category: "fashion",
    lat: 35.66068, lng: 139.69960,
    desc: "Large flagship of Japan's basics brand right on Meiji-dori.",
    hours: "11:00–21:00",
    tip: "Grab UT graphic tees you won't find abroad.",
  },
  {
    id: "gigo",
    name: "GiGO Shibuya (arcade)",
    jp: "GiGO渋谷",
    category: "otaku",
    lat: 35.66050, lng: 139.69820,
    desc: "Multi-floor game arcade — crane machines, rhythm games, purikura photo booths.",
    hours: "10:00–23:30",
    tip: "Top floors have the best UFO-catcher prizes.",
  },
  {
    id: "marui",
    name: "Marui (0101) Shibuya",
    jp: "渋谷マルイ",
    category: "department",
    lat: 35.66150, lng: 139.69870,
    desc: "Mid-range fashion department store on Koen-dori.",
    hours: "11:00–20:30",
    tip: "Often hosts anime/character pop-up collabs.",
  },
  {
    id: "modi",
    name: "Shibuya MODI",
    jp: "渋谷モディ",
    category: "department",
    lat: 35.66250, lng: 139.69955,
    desc: "Lifestyle/fashion complex with HMV&BOOKS and cafes.",
    hours: "11:00–21:00",
    tip: "HMV&BOOKS on the upper floors is a calm browse.",
  },
  {
    id: "miyashita-park",
    name: "MIYASHITA PARK",
    jp: "ミヤシタパーク",
    category: "park",
    lat: 35.66080, lng: 139.70240,
    desc: "Rooftop park over a stylish mall, with brands, a hotel and street-food alley below.",
    hours: "Park 8:00–23:00; shops 11:00–21:00",
    tip: "Great sunset rooftop lawn + climbing wall.",
  },
  {
    id: "shibuya-yokocho",
    name: "Shibuya Yokocho",
    jp: "渋谷横丁",
    category: "food",
    lat: 35.66130, lng: 139.70235,
    desc: "Neon food alley under Miyashita Park with regional Japanese eats, open late.",
    hours: "~11:00–05:00",
    tip: "Try dishes from different prefectures in one crawl.",
  },
  {
    id: "nonbei",
    name: "Nonbei Yokocho",
    jp: "のんべい横丁",
    category: "food",
    lat: 35.65985, lng: 139.70180,
    desc: "Tiny post-war alley of ~40 miniature bars, each seating a handful of people.",
    hours: "Evenings (varies by bar)",
    tip: "Atmospheric after dark; some bars have a small cover charge.",
  },
  {
    id: "center-gai",
    name: "Center Gai",
    jp: "センター街",
    category: "landmark",
    lat: 35.66040, lng: 139.69890,
    desc: "The buzzing pedestrian high street — fast food, fashion, arcades, youth culture.",
    hours: "24h (shops vary)",
    tip: "The heartbeat of Shibuya; cut through it to reach most spots.",
  },
  {
    id: "qfront",
    name: "QFRONT / TSUTAYA",
    jp: "QFRONT",
    category: "landmark",
    lat: 35.65920, lng: 139.69980,
    desc: "The big-screen building on the crossing; upstairs Starbucks has the classic view.",
    hours: "Starbucks ~07:00–22:30",
    tip: "Grab a window seat upstairs to watch the scramble.",
  },
  {
    id: "magnet",
    name: "MAGNET by SHIBUYA109 (rooftop)",
    jp: "MAGNET by SHIBUYA109",
    category: "viewpoint",
    lat: 35.65975, lng: 139.69955,
    desc: "'CROSSING VIEW' rooftop deck looking straight down onto the scramble.",
    hours: "Rooftop ~11:00–21:00",
    tip: "Cheaper crossing photo than SHIBUYA SKY, and closer to the action.",
  },
  {
    id: "cat-street",
    name: "Cat Street",
    jp: "キャットストリート",
    category: "fashion",
    lat: 35.66600, lng: 139.70400,
    desc: "Car-free boutique street linking Shibuya to Harajuku — streetwear and cafes.",
    hours: "Shops ~11:00–20:00",
    tip: "Walk it north to reach Harajuku in ~15 minutes.",
  },
];

/* Curated walking routes: ordered lists of spot ids. */
const ROUTES = [
  {
    id: "essentials",
    name: "Shibuya Essentials",
    emoji: "🌆",
    minutes: 60,
    blurb: "First-timer highlights: the crossing, 109, Center Gai and a rooftop view.",
    stops: ["hachiko", "scramble", "qfront", "shibuya109", "center-gai", "magnet", "miyashita-park"],
  },
  {
    id: "otaku",
    name: "Anime, Games & Records",
    emoji: "🎮",
    minutes: 90,
    blurb: "Pop-culture crawl through record crates, retro collectibles and game floors.",
    stops: ["hachiko", "mandarake", "disk-union", "tower-records", "parco", "nintendo-tokyo", "pokemon-center", "gigo"],
  },
  {
    id: "shopping",
    name: "Shopping Spree",
    emoji: "🛍️",
    minutes: 90,
    blurb: "Department stores and variety megastores, from the station up Koen-dori.",
    stops: ["scramble-square", "hikarie", "marui", "modi", "loft", "hands", "donki"],
  },
  {
    id: "food-night",
    name: "Food & Nightlife",
    emoji: "🍶",
    minutes: 75,
    blurb: "Neon alleys and riverside eats — best started late afternoon into evening.",
    stops: ["hachiko", "nonbei", "miyashita-park", "shibuya-yokocho", "center-gai", "stream"],
  },
];

// Expose globally for app.js (no bundler needed).
window.SHIBUYA = { CATEGORIES, SPOTS, ROUTES };
